<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Term report {{ $report['student']['admission_number'] }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1f2933; }
        h1 { color: #065f46; font-size: 18px; margin: 0 0 4px; }
        h2 { font-size: 13px; margin: 16px 0 8px; color: #065f46; }
        .muted { color: #6b7280; }
        .header { border-bottom: 2px solid #065f46; padding-bottom: 10px; margin-bottom: 12px; }
        .meta { width: 100%; }
        .meta td { padding: 2px 8px 2px 0; }
        table.scores { width: 100%; border-collapse: collapse; margin-top: 8px; }
        table.scores th, table.scores td { border: 1px solid #d1d5db; padding: 6px; }
        table.scores th { background: #ecfdf5; text-align: left; font-size: 10px; }
        .right { text-align: right; }
        .center { text-align: center; }
        .total { font-weight: bold; background: #f0fdf4; }
        .comment { border: 1px solid #d1d5db; padding: 10px; min-height: 60px; margin-top: 8px; }
        .footer { margin-top: 28px; width: 100%; }
        .sign { width: 45%; display: inline-block; }
        .line { border-top: 1px solid #111827; margin-top: 36px; padding-top: 4px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>School Management System</h1>
        <p class="muted">Ghana basic schools · Ghana Education Service · Terminal report</p>
        <p>
            Academic year {{ $report['academic_year'] }}
            · Term {{ $report['term'] }} of 3
        </p>
    </div>

    <table class="meta">
        <tr>
            <td><strong>Pupil:</strong> {{ $report['student']['display_name'] }}</td>
            <td><strong>Admission no.:</strong> {{ $report['student']['admission_number'] }}</td>
        </tr>
        <tr>
            <td><strong>Class:</strong> {{ $report['student']['class'] }} ({{ $report['student']['level'] }})</td>
            <td><strong>Class tutor:</strong> {{ $report['student']['class_tutor'] ?: '—' }}</td>
        </tr>
        <tr>
            <td><strong>Overall:</strong> {{ $report['summary']['overall'] !== null ? number_format($report['summary']['overall'], 1).'%' : '—' }}
                ({{ $report['summary']['grade'] }} · {{ $report['summary']['remark'] }})</td>
            <td><strong>Subjects recorded:</strong> {{ $report['summary']['recorded'] }}/{{ $report['summary']['offered'] }}</td>
        </tr>
    </table>

    <h2>Continuous assessment</h2>
    <p class="muted">Classwork 30% · Assignment 25% · Project 25% · Homework 20%</p>
    <table class="scores">
        <thead>
            <tr>
                <th>Subject</th>
                <th class="center">Classwork</th>
                <th class="center">Assignment</th>
                <th class="center">Project</th>
                <th class="center">Homework</th>
                <th class="center">Average</th>
                <th class="center">Grade</th>
                <th>Remark</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($report['subjects'] as $subject)
                <tr>
                    <td>{{ $subject['name'] }}</td>
                    <td class="center">{{ $subject['classwork'] !== null ? number_format($subject['classwork'], 0) : '—' }}</td>
                    <td class="center">{{ $subject['assignment'] !== null ? number_format($subject['assignment'], 0) : '—' }}</td>
                    <td class="center">{{ $subject['project'] !== null ? number_format($subject['project'], 0) : '—' }}</td>
                    <td class="center">{{ $subject['homework'] !== null ? number_format($subject['homework'], 0) : '—' }}</td>
                    <td class="center">{{ $subject['average'] !== null ? number_format($subject['average'], 1) : '—' }}</td>
                    <td class="center">{{ $subject['grade'] }}</td>
                    <td>{{ $subject['remark'] ?: $subject['band'] }}</td>
                </tr>
            @endforeach
            <tr class="total">
                <td colspan="5">Overall term performance</td>
                <td class="center">{{ $report['summary']['overall'] !== null ? number_format($report['summary']['overall'], 1) : '—' }}</td>
                <td class="center">{{ $report['summary']['grade'] }}</td>
                <td>{{ $report['summary']['remark'] }}</td>
            </tr>
        </tbody>
    </table>

    <h2>Class tutor’s comment</h2>
    <div class="comment">{{ $report['teacher_comment'] ?: 'No comment recorded for this term.' }}</div>

    <table class="footer">
        <tr>
            <td class="sign">
                <div class="line">Class tutor</div>
            </td>
            <td class="sign">
                <div class="line">Headteacher</div>
            </td>
        </tr>
    </table>
    <p class="muted">Generated by the School Management System · {{ now()->format('d M Y') }}</p>
</body>
</html>
